### ISSUE TITLE
Hello World with several regions

### ISSUE THREAD

**Issue by HansKrJensrud** [PrismLibrary/Prism-Samples-Wpf#1]
I have just added a few more regions to the MainWindow in the Hello World sample. The regions are TopRegion, LeftRegion, MainRegion (as before), RightRegion and BottomRegion, and placed "Hello World" in the TopRegion. The idea is that this structure may remain relative stable and recognizable as more advanced samples are developed later. My first and very, very tiny contribution to this project may be to share a zip-file containing this solution with you.

**Comment by brianlagunas** [comment]
How about submitting a pull request?  We can also throw some views in each of those regions.  A top view, a bottom view, etc.

**Comment by HansKrJensrud** [comment]
Not sure I'm able to do this. "Create pull request" is greyed out here. I may not have the appropriate user rights.

**Comment by brianlagunas** [comment]
You have to fork the repo first, make changes, then submit your PR
