### ISSUE TITLE
*System.ObjectModel* and *System.Runtime* missing references

### ISSUE THREAD

**Issue by Sergey-Nosov-GH** [PrismLibrary/Prism-Samples-Wpf#10]
Hi,

Brand new user here trying the Prism framework for the first time. Cloned the **Prism-Samples-Wpf** solution. Unfortunately, when trying to build, getting the missing reference errors about the _System.ObjectModel_ and _System.Runtime_ assemblies.

After adding those assembly references manually, getting the following error message: “Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.”

Quick search on Google indicates that perhaps Windows 8 at minimum is required. Building the project with Visual Studio 2013 Update 5 under Windows 7. Is Windows 8 or higher really required, or is something else amiss?

Thank you.

**Comment by brianlagunas** [comment]
Make sure you are using .NET 4.5 or greater.

**Comment by Sergey-Nosov-GH** [comment]
Thank you, your reply pointed me in the right direction.

The development machine actually has .NET Framework 4.6 installed.
**Retargeting both _ModuleA_ and _HelloWord_ packages from .NET 4.5.2 to .NET 4.6 fixed the errors.**

This is somewhat concerning. We do not want things to break, just because a fresh in-place .NET framework update is installed.

**Comment by brianlagunas** [comment]
hmm... this is interesting since it should work just fine with .NET 4.5+.  Well, at least you got it figured out for your scenario.
