### ISSUE TITLE
why do wpf sample need prism-unity?

### ISSUE THREAD

**Issue by LeiYangGH** [PrismLibrary/Prism-Samples-Wpf#105]
`prism-unity` is a seperate library from `prism-wpf`, why cannot the **wpf** samples run using `prism-core` and `prism-wpf` alone?

**Comment by brianlagunas** [comment]
Prism needs a container to function properly. Unity is one of those containers.

**Comment by LeiYangGH** [comment]
is it possible to let prism-wpf to have its own container? is wpf first class citizen in prism?

**Comment by brianlagunas** [comment]
Prism can use any DI container. It has built-in support for Unity and DryIoC. Yes, Prism supports WPF, Xamarin.Forms, Uno Platform, and MAUI.
