### ISSUE TITLE
want .net framework samples

### ISSUE THREAD

**Issue by LeiYangGH** [PrismLibrary/Prism-Samples-Wpf#106]
prism is great but due to some restrictions i cannot use the .net core. 
when i use .net framework 4.8 wpf project with vs2022, so far almost everything i needed can be found in the samples and can run,  except the dialogservice one. the samples(as well as the documents) are using prsim9, while .net framework 4.8 can only use prism 8.1.97 or lower, under which the dialogservice sample syntax cannot even compile(for examle, `DialogCloseListener` couldn't be found, [samples url](https://github.com/PrismLibrary/Prism-Samples-Wpf/blob/master/26-UsingDialogService/UsingDialogService/ViewModels/NotificationDialogViewModel.cs#L30).

Could you add one .net framework dialogservice sample, or just point me to other resources about this topic.  i searched github/google but they are most all using .net core, or using too old prism versions.

is it possible for me to clone prism code and copy the DialogCloseListener code into my project then try to compile? could anyone explain why we cannot use prism9 in .net framework 4.8 wpf project?

**Comment by brianlagunas** [comment]
There are some breaking changes coming for Dialogs in v9. You just have to fix the samples by implementing the `IDialogAware` interface to get the new member names.
