### ISSUE TITLE
Navigation sample slightly complicated

### ISSUE THREAD

**Issue by joeizang** [PrismLibrary/Prism-Samples-Wpf#13]
Hi guys,
great work with prism 6. I think the navigation quick start is kinda complicated with the modules in there and MEF. Is it possible to create a much simpler sample that one could learn from. I have the quick start in visual studio and I can make sense of some of it but the rest just seems different from when I don't have modularity enabled with Unity and just have 5 views I want to navigate to for example. Can you guys help with that? Hope it ain't too much to ask.

God bless.

**Comment by brianlagunas** [comment]
All samples have been redone to simply all the concepts into more focused samples that should be easier to understand.
