### ISSUE TITLE
Centering dialog box to Shell

### ISSUE THREAD

**Issue by frankwwu** [PrismLibrary/Prism-Samples-Wpf#16]
With Interactivity, I know how to center a dialog box to its immediate owner. In my case, the dialog box owner is no in the center of the Shell. And I need to center the dialog box to the Shell. I have spent some time on it, but still have no clue. Is it doable with Interactivity? Or I need a different way? TIA.

**Comment by brianlagunas** [comment]
Just use the WindowStartupLocation property:

https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Wpf/Interactivity/PopupWindowAction.cs#L50
