### ISSUE TITLE
ViewSwitching with Unity

### ISSUE THREAD

**Issue by kamlendra** [PrismLibrary/Prism-Samples-Wpf#19]
HI, for Prism every example is available  with unity. but the View Switching example is using MEF only. can this be available with unity as well.
Regards,
Kamlendra

**Comment by brianlagunas** [comment]
Sure. A PR would be great :)

**Comment by kamlendra** [comment]
Thanks for accepting my request. PR? I will be waiting for Unity version.

**Comment by brianlagunas** [comment]
PR = Pull Request.  This means that you can create the sample when you have time and the add it to the samples repo.

**Comment by kamlendra** [comment]
Sure.

**Comment by dvorn** [comment]
@brianlagunas Do we want to replace MEF sample with Unity sample, or add a new Unity sample?

**Comment by brianlagunas** [comment]
We can just add the Unity.  Although I would rather not have any MEF samples, we have to have them since MEF has been supported in Prism for WPF for a long time now.  We won't be adding any new MEF samples though :)
