### ISSUE TITLE
Unable to locate ServiceLocatorImplBase.cs in Module in constructor

### ISSUE THREAD

**Issue by ghost** [PrismLibrary/Prism-Samples-Wpf#23]
Hi,

I have made a new WPF project, and implemented the same structure as you have for your hello world sample. My problem is in the module class' constructor when i set the regionManager parameter to the local field and try step out of the constructor, I get directed to a warning screen stating that the application is unable to locate the ServiceLocatorImplBase.cs file.

My platform target is Any CPU as it is a normal WPF project, and my target framework is 4.6.1.

**Comment by brianlagunas** [comment]
Make sure you are using the correct nuget packages.
