### ISSUE TITLE
The DemoApplication ViewSwitchingNavigation does not build

### ISSUE THREAD

**Issue by olippuner** [PrismLibrary/Prism-Samples-Wpf#26]
The DemoApplication ViewSwitchingNavigation does not build.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Resource file "obj\x86\Debug\View_Switching.AcceptanceTest.TestData.ControlIdentifiers.resources" has an invalid name. 
The item metadata "%(FullPath)" cannot be applied to the path "obj\x86\Debug\View_Switching.AcceptanceTest.TestData.ControlIdentifiers.resources". obj\x86\Debug\View_Switching.AcceptanceTest.TestData.ControlIdentifiers.resources
	View-Switching.AcceptanceTest		
```	

Build configuration X86
Windows-7 with VS Enterprise 2015 

Problem is caused by 260 CHAR limitation in windows-pathlengths

Build error occurs when project is hosted in path
L:\wrk\OLI3\VS2015.CSharp.Dev\VS2015\C#\20161207_mvvm_Prisma\Prism-Samples-Wpf-master\View-Switching Navigation_Desktop

Build error nomore occurs with shortened path
L:\VS2015\Modularity

Problem
Obviously the demo program does not handle the possible problems with overlong pahtnames. Itself it uses quite long sub-pathnames. The builderror is in no way helpful or indicating how to correct the situation to avoid failure. I found the solution by pure intution. Such severe failures shouldn't be possible 
in simple demo programs, that have a promotional and educational function.

**Comment by briannoyes** [comment]
I'm not sure what you expect to do about that. We don't control Windows maximum path lengths, we don't control the build errors VS gives you for that kind of problem, nor do we control where the developer tries to put the code on their machine. You can encounter this with any project, no matter how short the folder/file names are if you put it in too long of a folder path location. Yes, the folder/file names could be made shorter, but at the sacrifice of them being more self-documenting, which is important in samples. 

I've got the code 5 folders (not tiny named ones either) deep on my machine, so its not like it only works if you build it at the root of the drive.

I don't see this as something we are going to change. Much bigger fish to fry with our limited time to work on Prism.
