### ISSUE TITLE
are there any more complex demo for wpf?

### ISSUE THREAD

**Issue by gitlsl** [PrismLibrary/Prism-Samples-Wpf#27]
any demo like `View-Switching Navigation` before is more complex  , but it was deleted ?

**Comment by brianlagunas** [comment]
No. That was a bad example.  The new samples are more concise and concentrate on single topics.  All core concepts you need to know are in the current samples.

**Comment by Ghislain1** [comment]
Hi Brian,
I m very new  in Prism. 
Can you help me with some  example how to use RadDocking(telerik Control) with Prism 6.1?
Prism works fine with Dockmanager (Xceed) But my Compagny  want to Switch to  Telerik Library...  
Telerik Support provides some examples but ist not similary To Dockmanger

Thank you a lot.
Ghislain from Germany

**Comment by brianlagunas** [comment]
@Ghislain1 I'm sorry, but I do not provide support for Telerik controls :)
