### ISSUE TITLE
Is there any sample code for RegionBehaviors?

### ISSUE THREAD

**Issue by juniair** [PrismLibrary/Prism-Samples-Wpf#28]
I would like to know how to implement the RegionBehaviors. Could you please raise the sample code for RegionBehavior?

**Comment by brianlagunas** [comment]
Please watch the Prism Problems and Solutions courses on Pluralsight listed on the Support section of the Readme file. These courses show you more advanced topics such as region behaviors.

https://github.com/prismlibrary/prism#support
