### ISSUE TITLE
Create Bootstrapper instance

### ISSUE THREAD

**Issue by The-Futurist** [PrismLibrary/Prism-Samples-Wpf#30]
Can you help?

Bootstrapper seems to be an abstract class so when I copy this code:

Prism-Samples-Wpf/1-BootstrapperShell/BootstrapperShell/App.xaml.cs

It fails to compile - am I misunderstanding something?

Thx

**Comment by brianlagunas** [comment]
you need to copy the XAML too.  Just download the Prism Template Pack and use the File -> New -> Project Templates

https://marketplace.visualstudio.com/items?itemName=BrianLagunas.PrismTemplatePack
