### ISSUE TITLE
error in sample 11-UsingDelegateCommands when using V6.3

### ISSUE THREAD

**Issue by sanderobdeijn** [PrismLibrary/Prism-Samples-Wpf#32]
I get the following error.
CS1593	Delegate 'Expression<Func<bool>>' does not take 1 arguments
I expect something has changed in version V6.3 the sample does works is V6.2.

According to this blog post the parameter in the method ObservesCanExecute needs to be removed.
[http://brianlagunas.com/prism-6-3-release/](http://brianlagunas.com/prism-6-3-release/)

**Comment by brianlagunas** [comment]
PR?
