### ISSUE TITLE
Is there any plan to update the samples to new version of Prism 7?

### ISSUE THREAD

**Issue by sclcwwl** [PrismLibrary/Prism-Samples-Wpf#35]
The new version have  introduced some breaking new feature and the samples need to be updated to run.

**Comment by bartlannoeye** [comment]
Our current focus is on the library. If anyone feels like stepping in, please do so and send a pull request.

**Comment by brianlagunas** [comment]
Also, v7 hasn't been released. It doesn't make sense to update them until v7 has been released.
