### ISSUE TITLE
Updating the packages results in build errors

### ISSUE THREAD

**Issue by vknht** [PrismLibrary/Prism-Samples-Wpf#37]
Hello,

if you Update the packages to the newest version via NuGet-Packet-Manager, you cannot build the Projects anymore.

**Comment by bartlannoeye** [comment]
To which version are you updating? The pre-release versions of v7 have breaking changes, please read https://github.com/PrismLibrary/Prism/releases/tag/7.0.0-pre5

**Comment by vknht** [comment]
Hello,

the only thing I am updating are these packages:

![prism_update](https://user-images.githubusercontent.com/34534652/34521527-6c693c8a-f08e-11e7-9821-bc8a880d0264.png)

CommonServiceLocator: 1.3.0 -> 2.0.1
Unity: 4.0.1 -> 5.5.3
  
Edit: I should mention, that I tried updating the "BootstrapperShell"-Project, but it should also apply to all other Projects as well.

**Comment by bartlannoeye** [comment]
Unity v5 is not compatible with Unity v4, same goes for CommonServiceLocator which introduces .Netstandard.

Prism v6 depends on the lower versions, to use the new version you will need Prism v7, which has other breaking changes as well.

See: 
- https://github.com/PrismLibrary/Prism/issues/1226
- https://github.com/PrismLibrary/Prism/issues/1211
