### ISSUE TITLE
are you sure this stuff works?

### ISSUE THREAD

**Issue by kcabral817** [PrismLibrary/Prism-Samples-Wpf#38]
The latest release with 7.0 and Unity does not work with a bootstrapper.  
this does not compile

protected override DependencyObject CreateShell()
        {
            return Container.Resolve<MainWindowView>();
        }

**Comment by brianlagunas** [comment]
yeah it works, you're just doing it wrong. Prism for WPF 7.0 hasn't released yet, only for Xamarin.Forms.  You should still be using the 6.3 packages for WPF.

**Comment by kcabral817** [comment]
Thank you!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by robertwharvey** [comment]
@brianlagunas: While I'm excited about the new Unified API in Prism 7, I will defer to your judgement and stay with Version 6 for WPF until Version 7 is officially released.  Thanks for the great work!
