### ISSUE TITLE
A proposal to improve discovering modules in directory

### ISSUE THREAD

**Issue by dprevato** [PrismLibrary/Prism-Samples-Wpf#39]
I would like to add my two cents (maybe one only)...
I propose to modify the postbuild macro in the project "07-Modules - Directory" with this one:

**xcopy "$(TargetDir)$(TargetName)*$(TargetExt)" "$(SolutionDir)$(SolutionName)\$(OutDir)Modules\" /Y /S**

In this way, you can copy with the module .DLL also the localization satellites .DLL; you don't need to manually copy them in the "Modules" directory, and all the culture changes get instantly applied in the modules.

The final result will be, for example (for italian localization): module .DLLs in Modules dir, subdir "it-IT" containing the italian localization DLLs for all the modules.

Daniele Prevato

**Comment by brianlagunas** [comment]
Sure. Makes sense. Submit your PR and I'll get it merged.
