### ISSUE TITLE
File path problem in windows batch

### ISSUE THREAD

**Issue by IOL0ol1** [PrismLibrary/Prism-Samples-Wpf#42]
Open the project "07-Modules - Directory"  with VS2017,
Bulid - Rebuild solution, 
The Output window display :
 error MSB3073: The command "xcopy "D:\Projects\Prism-Samples-Wpf\07-Modules - Directory\ModuleA\bin\Debug\ModuleA*.dll" "D:\Projects\Prism-Samples-Wpf\07-Modules - Directory\\**Modulesbin**\Debug\Modules" **/Y /S**" exited with code 2.

1.Modulesbin should be Modules\bin
2.exited with code 2 because Debug\Modules directory does not exist, 

I change 
`xcopy "$(TargetDir)$(TargetName)*$(TargetExt)" "$(SolutionDir)$(SolutionName)$(OutDir)Modules" /Y /S`
to
`xcopy "$(TargetDir)$(TargetName)*$(TargetExt)" "$(SolutionDir)$(SolutionName)/$(OutDir)Modules" /I /Y /S`
it works.

**Comment by zdlzyw** [comment]
Currently, there is still an issue. The generated location of ModuleA.dll is the main path of the project: Prism-Samples-Wpf-master\Prism-Samples-Wpf\bin\Debug\netcoreapp3.1. 
The code is: `$(SolutionDir)$(SolutionName)\bin\Debug\netcoreapp3.1.`
The App.config is looking for this path: assemblyFile="ModuleA.dll, Prism-Samples-Wpf-master\07-Modules - AppConfig\Modules\bin\Debug\netcoreapp3.1.
In reality, the PostBuildEvent of ModuleA's CSPROJECT should be 
`$(SolutionDir)\07-Modules - AppConfig\Modules\bin\Debug\netcoreapp3.1.`
