### ISSUE TITLE
Navigation Without push to history

### ISSUE THREAD

**Issue by 3DNDev** [PrismLibrary/Prism-Samples-Wpf#43]
Is there any way to navigate with Prism (using RegionManager.RequestNavigate) and prevent prism pushing the view in navigation History.

I want Navigate from ViewA to ViewB and From ViewB To ViewC but when navigating from A to B i won't historisize the viewB , So when i call GoBack from ViewC then ViewA appears because the ViewB not exist in History of navigation.

Exemple :

I am in ViewA 
Call RequestNavigate(ViewB) -----> Show ViewB
Call RequestNavigateWithoutHistorisize(ViewC) ----> Show ViewC
Call GoBack() -------> Show ViewA

Thanks

**Comment by brianlagunas** [comment]
If you are using the latest CI build or Preview you can implement IJournalAware to opt-out of persisting a view in history.
