### ISSUE TITLE
xcopy exited with code 2 in 07-Modules - Directory sample

### ISSUE THREAD

**Issue by jebissey** [PrismLibrary/Prism-Samples-Wpf#47]
Hi,

There is a little mistake in Post-build event command line

Original line is :
xcopy "$(TargetDir)$(TargetName)*$(TargetExt)" "$(SolutionDir)$(SolutionName)$(OutDir)Modules" /Y /S

The fix is :
xcopy "$(TargetDir)$(TargetName)*$(TargetExt)" "$(SolutionDir)$(SolutionName)\$(OutDir)Modules\" /Y /S

Regards

**Comment by brianlagunas** [comment]
What' the difference? Can you bold the change?  Also we accept PR's

**Comment by jebissey** [comment]
Sorry, this is the corrected line

xcopy "$(TargetDir)$(TargetName)*$(TargetExt)" "$(SolutionDir)$(SolutionName)\$(OutDir)Modules\" /Y /S

There are missing \ after "$(SolutionName)".
I also add another one after "Modules".

**Comment by jebissey** [comment]
My \ are deleted ...
A try with \\

xcopy "$(TargetDir)$(TargetName)*$(TargetExt)" "$(SolutionDir)$(SolutionName)\\$(OutDir)Modules\\" /Y /S

**Comment by jebissey** [comment]
Yes it ok with double \\
