### ISSUE TITLE
Problem in Call Window not UserControl

### ISSUE THREAD

**Issue by aghili371** [PrismLibrary/Prism-Samples-Wpf#50]
I want to call window but all examples work with userControl.

I'm using BootstrapperShell and when i call the form from my Ribbon menu, loading grid working really slow but in the main page is work well. 
I tested by calling window its work as well too. but i can't embed the window in the main form and it does not work.
in this code i have WindowKostenstelle this form az window, not user control:
 _regionManager.RequestNavigate(RegionNames.ContentRegionName, "WindowKostenstelle" );

**Comment by brianlagunas** [comment]
I'm sorry, but your issue is not clear. If this is a general question you should post this on a different forum such as StackOverflow.

**Comment by aghili371** [comment]
my question is how i can use prism in WPF with windows form not with UserControl ? Is it possible to call windowsform ?

i have a problem in loading the data. it's super slow when i call UserControl.

**Comment by brianlagunas** [comment]
Prism for WPF is not compatible with WinForms
