### ISSUE TITLE
Bootstrapper Or Not - PRISM 7

### ISSUE THREAD

**Issue by Joel4JC** [PrismLibrary/Prism-Samples-Wpf#55]
I'm brand new to PRISM and Unity and I'm trying to work my way through this process, please excuse the basic questions. I download the PrismDemo code from Brian Lagunas' "MVVM Made Simple with Prism" which used Prism 6. Using 'Manage NuGet Packages" in Visual Studio, I updated all the Prism and Unity Libraries. In the Bootstrapper.cs it says theUnityBootstrapper Base Class is obsolete, got it. I change the base class from UnityBootstrapper to PrismApplication, done. It also says "This will require updating the App.xaml and App.xaml.cs files", however I can't find any documentation that tells me what needs to be changed. Here in the Prism-Samples-Wpf, in 01-BoostrapperShell, still uses UnityBootstrapper with the same warning/information message. I know it will still work, but I would prefer not to use obsolete objects and use Prism 7 as it is intended to be used. Can someone point me to a resource, YouTube or blog post that will help me get pass this. Thanks in Advance.

**Comment by brianlagunas** [comment]
Did you look at the other samples? All the samples show you exactly what needs to be done.

**Comment by sperazza** [comment]
I had the same question , i found this
App.xaml.cs

``` 
internal partial class App : PrismApplication
{
   protected overide void RegisterTypes(IContainerRegistry containerRegistry)
  {
  }

  protected override Window CreateShell()
  {
   return Container.Resolve<MainWindow>();
  }
 }
``` 
App.xaml
``` 
<prism:PrismApplication x:Class="myMain.App"
                                    x:ClassModifier="internal"
                                    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                                    xmlns:prism="http://prismlibrary.com/"
   <Application.Resources/>
</prism:PrismApplication>
```
