### ISSUE TITLE
Portable Class Library to .NET Standard

### ISSUE THREAD

**Issue by tonecool** [PrismLibrary/Prism-Samples-Wpf#56]
I was just checking new WPF PRISM example from [here](https://github.com/PrismLibrary/Prism-Samples-Wpf/tree/master/12-UsingCompositeCommands).
There is a project called UsingCompositeCommands.Core which is created PLC. By using short guide from [here](https://montemagno.com/how-to-convert-a-pcl-library-to-net-standard-and-keep-git-history/), I was able to build it as .NET Standard 2.0 and example works as well after .net framework version change.
Do you think this is the right way to do it for new projects as well ?
If you do, maybe we can update example too ;)

**Comment by brianlagunas** [comment]
Use .NET Standard if it makes sense for your projects. No need to spend time updating samples to .NET Standard. They are being upgraded to .NET Core 3 instead.
