### ISSUE TITLE
Rewrite the code to Task base asynchronous pattern

### ISSUE THREAD

**Issue by YehudahA** [PrismLibrary/Prism-Samples-Wpf#6]
ViewSwitchingNavigation sample project includes heavy use the old APM pattern.
Who will start now to learn about IAsyncResult, just because he want to learn about prism?

**Comment by briannoyes** [comment]
You are right, need to get that updated. Hopefully someone from the community who it bothers will step in and submit a pull request with those fixes (hint hint) :)

Seriously though, please do if you have time. We'll keep this in the backlog if not and try to get to it when we can.

**Comment by YehudahA** [comment]
OK, may be I will do it.

**Comment by YehudahA** [comment]
I did it, and I'm trying to send a pull request but I get a message that i don't have permissions.

**Comment by bartlannoeye** [comment]
I suppose you did commit to your own fork and not this repository? As others can send a PR, I think everything permission-wise should be ok (unless one of the brians changed it lately).

**Comment by briannoyes** [comment]
No changes that I am aware of. 

So did you get your changes checked in to your own fork and push'ed up to GitHub? Is the error happening when you press the "Compare, Review and Create a Pull Request" green button to the upper left of the list of files in your fork?

If you can give some more information we can try to help you through it. Or if you just want to send me a zip of what you have I can get it checked in for you but will still need you to sign a CLA:
https://cla2.dotnetfoundation.org/

Thanks
Brian

**Comment by YehudahA** [comment]
I hope I did everything right ..

https://github.com/YehudahA/Prism-Samples-Wpf/pull/1

**Comment by briannoyes** [comment]
Your pull request was under your own repo, not the Prism one. There were a number of changes I would have made to it anyway, so just went and updated the sample myself.

**Comment by YehudahA** [comment]
OK, a good job, but some comments:
- I think that using ObservableCollection as Notify-property is anti-pattern.
  Instead of:

``` csharp
        public ObservableCollection<Meeting> Meetings
        {
            get { return meetings; }
            set { SetProperty(ref meetings, value); }
        }
```

Instead of this, we can use `List<Meeting>`, or like you did in ContactsViewModel: `mettings.ForEach ....`

But in my opinion, the best way to initialize collection is using extension method:

``` csharp
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace ViewSwitchingNavigation.Infrastructure
{
    public static class ObservableCollectionExtensions
    {
        public static void AddRange<T> (this ObservableCollection<T> targetCollection,IEnumerable<T> source)
        {
            foreach(T item in source)
            {
                targetCollection.Add(item);
            }
        }
    }
}
```

//====================//
 Instead of:

``` csharp
            contactsServiceMock
                .Setup(svc => svc.GetContactsAsync())
                .Returns(Task.FromResult(contacts));
```

You can write:

``` csharp
            contactsServiceMock
                .Setup(svc => svc.GetContactsAsync())
                .ReturnsAsync(contacts);
```
