### ISSUE TITLE
InvokeCommandAction Default Selected Item to first item

### ISSUE THREAD

**Issue by OzBob** [PrismLibrary/Prism-Samples-Wpf#62]
How could the first item in the ListBox be auto-selected when the ListBox ItemsSource has been updated?

https://github.com/PrismLibrary/Prism-Samples-Wpf/blob/master/29-InvokeCommandAction/UsingInvokeCommandAction/Views/MainWindow.xaml#L24

Adding

```
 SelectedItem="{Binding SelectedItemText, Mode=OneWay}"
```

to the ListBox doesn't work.

Calling

```
OnItemSelected(Items.ToArray());
```
in the MainWindowViewModel ctor doesn't set the ListBox selection to ItemList.SelectedItems[0].

**Comment by brianlagunas** [comment]
You should ask your questions on another forum such as StackOverflow
