### ISSUE TITLE
Request for Generic Host (.NET Core 3) + Prism + WPF sample - Can contribute

### ISSUE THREAD

**Issue by bmarinov** [PrismLibrary/Prism-Samples-Wpf#63]
**Is your feature request related to a problem? Please describe.**

I am missing a sample or some documentation explaining the correct way to handle this. I want to set up a **.NET Core WPF** application which uses **Prism** and whose Lifetime / DI / Configuration is controlled (or supported) by a [Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.1).
In my case I am utilizing **DryIoC** as my ioc container of choice.

Right now WPF does not do a great job of using newer framework features, there are some open issues on GH like [dotnet/wpf:499](https://github.com/dotnet/wpf/issues/499). So even if the WPF integration will not be perfect, some aspects can already be put to good use: **IoC**, **Configuration** and **Hosted Services** for [background tasks](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1).

**Describe the solution you'd like**
Clear guidelines for bootstrapping an application using a Generic Host, sample included.

I am having trouble finding definitive information on instantiating the IoC container myself. There is a hook that seems to be doing that - `CreateContainerExtension()`. Is this the correct way to go about it? If yes, is its intended use documented and if not - can we improve the documentation?

**Describe alternatives you've considered**

I managed to get things going with a couple of extra lines, but I'm sure that there are better ways to go about that (eg utilizing the aforementioned `CreateContainerExtension` method). 

Additional dependencies:
- `Microsoft.Extensions.Hosting` - this dependency is for the generic host feature.
- `DryIoc.Microsoft.DependencyInjection` - package with extension methods for the dryioc adapter, usually used in the context of ASPNET Core.

The App.xaml.cs actually looks _alright_, services can be registered as usual and resolved via `base.Container` and via `_host.Services` since im basically just adding more registrations to the instantiated container. 

```cs
// App.xaml.cs

protected override void RegisterTypes(IContainerRegistry containerRegistry)
{
    containerRegistry.Register<ServiceA>();
}

protected override Window CreateShell()
{
    _host = new HostBuilder()
        .ConfigureServices(x =>
        {
            x.AddTransient<ServiceB>();
        })
        .UseServiceProviderFactory(new DryIocServiceProviderFactory(Container))
        .Build();

    _host.Start();
    // ServiceA and ServiceB can be resolved here.

    return _host.Services.GetService<MainWindow>();
}
```

While implementing the DryIoC Service Provider Factory it became obvious that I'm going down the wrong path. As you will see, I am taking the instantiated container and casting it to the known underlying type. Normally you would new up a container in `CreateBuilder` so this current implementation feels wrong.

```cs
// DryIocServiceProviderFactory.cs
internal class DryIocServiceProviderFactory : IServiceProviderFactory<IContainer>
{
    private readonly DryIocContainerExtension _containerProvider;

    public DryIocServiceProviderFactory(IContainerProvider containerProvider)
    {
        // I should not be doing this..
        _containerProvider = containerProvider as DryIocContainerExtension;
    }

    public IContainer CreateBuilder(IServiceCollection services)
    {
        return _containerProvider.Instance.WithDependencyInjectionAdapter(services);
    }

    public IServiceProvider CreateServiceProvider(IContainer containerBuilder)
    {
        return containerBuilder.Resolve<IServiceProvider>();
    }
}
```

**Describe suggestions on how to achieve the feature**

So if I am correct, I need to somehow use the `CreateContainerExtension()` method.  
The following does **not** work, Prism services are missing from the container and cannot be resolved.

```cs
protected override IContainerExtension CreateContainerExtension()
{
    return new DryIocContainerExtension(new DryIoc.Container());
}
```
I thought that these would get registered in the container I return from this method.

Hopefully I did not miss anything obvious in the documentation, I searched but found nothing. I would love to contribute to the project and push such a sample, but before doing that I need a bit of hand holding. Thanks!

**Comment by brianlagunas** [comment]
Read this: https://prismlibrary.com/docs/xamarin-forms/dependency-injection/add-custom-container.html

While I don't see the point of trying to use the Microsoft Generic Host, if you want this to work in your app, you are responsible for writing the code and figuring it out. Prism will not create a sample or officially support the generic host.

**Comment by bmarinov** [comment]
Thanks for the reply and for pointing me in the right direction @brianlagunas, I didnt think of looking in the Xamarin docs for this. This should do the trick.

Regarding the Generic Host: is the reason for not supporting it the lack of official support from microsoft, e.g. the aforementioned dotnet/wpf/499? Or is it unclear why it would be useful in the context of a WPF application. Maybe ASPNET Core has warped my perception so much that I am missing the wood for the trees.
This question might or might not belong here.

Kind regards!

**Comment by brianlagunas** [comment]
There is no use for the Generic Host in a Prism application. Prism already supports DI via a number of DI containers.

**Comment by drusteeby** [comment]
> Read this: https://prismlibrary.com/docs/xamarin-forms/dependency-injection/add-custom-container.html
> 
> While I don't see the point of trying to use the Microsoft Generic Host, if you want this to work in your app, you are responsible for writing the code and figuring it out. Prism will not create a sample or officially support the generic host.

Updated link to the documentation for anyone looking for this in the future: https://prismlibrary.github.io/docs/dependency-injection/add-custom-container.html
