### ISSUE TITLE
Updating to .NET Core 3.1 LTS

### ISSUE THREAD

**Issue by seesharprun** [PrismLibrary/Prism-Samples-Wpf#64]
I'm interested in updating these samples to .NET Core 3.1.

I already have a sample application out there showing how to do a lot of these features in .NET Core.

If you want to preserve these demos for .NET Framework developers, would you be willing to take contributions to a new repository?

**Comment by seesharprun** [comment]
Here's the sample project: https://github.com/seesharprun/Prism-Samples-Wpf-NetCore

It's a complex example, but I would break it down into steps like you did here if you were interested. I can also help fill-in the WPF documentation by pointing to the .NET Core 3.1 LTS samples

**Comment by brianlagunas** [comment]
Thank you for the very kind offer. However, the current samples are already .NET Core 3.  We would greatly appreciate any help with the documentation as that is a massive gap in our content at the moment.

**Comment by seesharprun** [comment]
They are running on 3.0 which will reach End of Support in 32 days: https://dotnet.microsoft.com/platform/support/policy/dotnet-core

Can I do a minor update of the samples to 3.1 (the LTS version) and contribute to the docs?

**Comment by brianlagunas** [comment]
I was not aware that the 3.0 support cycle was so short. Thanks for letting me know. It would be great if you could update all the samples to 3.1.  We would very much appreciate any contributions you can make including documentation.

**Comment by seesharprun** [comment]
FYI: There are a couple of additional changes to make.

For example, UnityBootstrapper gives a compiler warning since it has been replaced with PrismApplication.

I am going to start work now and open a PR early so you can keep tabs on progress.

**Comment by brianlagunas** [comment]
Leave the one sample showing the use of the bootstrapper alone. That is specifically for the Bootstrapper.

**Comment by seesharprun** [comment]
Maybe I can suppress the compiler warning for 01-* just to illustrate using the UnityBootstrapper.

**Comment by brianlagunas** [comment]
No need to suppress it. We still want the warning.

**Comment by seesharprun** [comment]
There's a two additional changes I would recommend:
- Bring ``Prism.Unity`` from ``7.2.0.1367`` to ``7.2.0.1422``
- Remove ``AssemblyName`` property, it's doesn't do anything since you use the same name for the csproj property.

How do you feel about those two changes?

**Comment by brianlagunas** [comment]
Yes, you can upgrade Prism to the latest, and I am okay with removing the AssemblyName

**Comment by dansiegel** [comment]
To make this easier, @seesharprun please match what we've already done for the Prism.Forms samples... 

- Add a Directory.Build.props file at the base of the repo.. you can see a sample [here](https://github.com/PrismLibrary/Prism-Samples-Forms/blob/master/Directory.Build.props)
- Update the PackageReference Version to `$(PrismVersion)` for any of the Prism packages.

**Comment by seesharprun** [comment]
Moving conversation to #65 

I did the first sample there, and you can track progress in real time. I can already tell that 07 will be a doozy since they rebuilt how Pre/Post build tasks work and there's some variance between Visual Studio, other IDEs and .NET CLI.
