### ISSUE TITLE
Deprecated request samples

### ISSUE THREAD

**Issue by fatihyildizhan** [PrismLibrary/Prism-Samples-Wpf#66]
I was looking for Custom Requests with `IDialogService`. The samples 25 to 29 are using `INotification`.

![notification](https://user-images.githubusercontent.com/602600/76087273-e2b69000-5fc6-11ea-8a91-55d5a077a327.png)

Then I saw this page and achieved my goal.
https://prismlibrary.com/docs/wpf/dialog-service.html

I'm sure you are aware of this but I just want to mention. Ready to run samples are nice to get it the big picture.

**Comment by brianlagunas** [comment]
I have removed the old interactivity samples. Thanks for the issue.
