### ISSUE TITLE
Why the state-based sample removed from Prism?

### ISSUE THREAD

**Issue by yanshouwang** [PrismLibrary/Prism-Samples-Wpf#68]
Before Prism 7.0 I can use state-based navigation to switch view state to Navigate to ListView's Item, but after Prism 7.0 I can't see that any more, so what's the correct way to Navigate when I click a ListView's item(the item is a ViewModel alreay exist so I can't use view-based Navigation)

**Comment by brianlagunas** [comment]
State-base navigation isn't really navigation. It's just updating the state of the VM. In your case the SelectedItem of the ListView. This is standard MVVM stuff, and nothing specific to Prism.
