### ISSUE TITLE
Could not find Registering Modules Using a XAML file

### ISSUE THREAD

**Issue by snehansh** [PrismLibrary/Prism-Samples-Wpf#70]
I could not find sample project for ‘Registering Modules Using a XAML file’ within ‘Prism-Samples-Wpf’. Include a sample project for ‘Registering Modules Using a XAML file’.

**Comment by snehansh** [comment]
If this is a valid issue, I can take the responsibility to make the change for this issue.

**Comment by brianlagunas** [comment]
I believe there is a bug in the way .NET Core 3 reads files on disk which causes an exception in the Prism catalog. You can try, but don't be surprised if it doesn't work :)
