### ISSUE TITLE
12-UsingCompositeCommands error

### ISSUE THREAD

**Issue by kaki104** [PrismLibrary/Prism-Samples-Wpf#73]
Hi

I am getting an error when building this project, but I can't find the cause.
https://github.com/PrismLibrary/Prism-Samples-Wpf/tree/master/12-UsingCompositeCommands

Error messages :
Severity	Code	Description	Project	File	Line	Suppression State
Error		The package reference 'Prism.Core' must have a version defined in 'C:\Users\kaki1\source\repos\Prism-Samples-Wpf\Packages.props'.	UsingCompositeCommands.Core	C:\Users\kaki1\source\repos\Prism-Samples-Wpf\12-UsingCompositeCommands\UsingCompositeCommands.Core\UsingCompositeCommands.Core.csproj	1	
Error		The package reference 'Prism.Wpf' must have a version defined in 'C:\Users\kaki1\source\repos\Prism-Samples-Wpf\Packages.props'.	ModuleA	C:\Users\kaki1\source\repos\Prism-Samples-Wpf\12-UsingCompositeCommands\ModuleA\ModuleA.csproj	1	

Steps 1 through 11 were built normally without errors.

My environment
Windows 10 version 2004
Visual Studio 2019 version 16.7.2

**Comment by dansiegel** [comment]
Thanks for reporting the issue. It seems I accidentally set the PackageReferences for WPF & Core to Include instead of update in the Packages.props. This has been fixed.
