### ISSUE TITLE
[Question] Is it possible to implement 07-Modules - LoadManual to xamarin

### ISSUE THREAD

**Issue by chc7042** [PrismLibrary/Prism-Samples-Wpf#81]
Hi @austindimmer 
i am beginer of Prism and Xamarin. i really need to implement "07-Modules - LoadManual" to our mobile application using Xamarin. i think it is possible to achieve but it difficult to me. how do you think about this?

**Comment by dansiegel** [comment]
@austindimmer this is not a place for questions. You can try the discussions tab on the Prism repo, or StackOverflow
