### ISSUE TITLE
Overall Solution file

### ISSUE THREAD

**Issue by jordyvaneijk** [PrismLibrary/Prism-Samples-Wpf#85]
Hi, 

I created a solution file that has all the examples in it. I would love to create a branch and push it so you can review it. It's easier than having to open a lot of solutions.

**Comment by brianlagunas** [comment]
sure, create a PR and let's see what you have.

**Comment by jordyvaneijk** [comment]
Done

**Comment by brianlagunas** [comment]
Thanks for the helpful PR
