### ISSUE TITLE
[Qusetion] Bootstrapper or App.g.i.cs change.. What's better?

### ISSUE THREAD

**Issue by Bantree96** [PrismLibrary/Prism-Samples-Wpf#91]
Please understand that I used a translator because I am not familiar with English.

If you look at the example, there are two ways to use "Bootstrapper" and to change "App.g.i.cs", which is the better way? And I would appreciate it if you could explain the difference between the two.

thank you.

**Comment by brianlagunas** [comment]
The bootstrapper is mainly used when developing plugins that do not have a WPF application associate with it. The PrismApplication class is used when you are building a WPF application.
