### ISSUE TITLE
Blank window samples

### ISSUE THREAD

**Issue by hrumhurum** [PrismLibrary/Prism-Samples-Wpf#97]
Many samples just show a blank white window without any visualizations or actions. For example, "08-ViewModelLocator" example demonstrates just a blank window without any visual hints about the state of a view model - was it actually wired or not? There are plenty of other similar "blank" samples that provide no way to determine whether they work or not.

**Comment by brianlagunas** [comment]
Closing as there are no actional items in this issue. Your comments were vague and not specific, and there were no recommendations or suggestion to make improvements.

**Comment by brianlagunas** [comment]
> For example, "08-ViewModelLocator" example demonstrates just a blank window without any visual hints about the state of a view model

If you look at the sample, you will see there is a binding in the view which shows the data binging working:

![image](https://github.com/PrismLibrary/Prism-Samples-Wpf/assets/835562/5444d34e-0b36-41b1-93d8-c5c353a0726b)

![image](https://github.com/PrismLibrary/Prism-Samples-Wpf/assets/835562/a2a43c84-cbba-4ef6-ac0e-476c05f8f1ab)
