### ISSUE TITLE
Why is it so hard to use regions?

### ISSUE THREAD

**Issue by dsynclabsllc** [PrismLibrary/Prism-Samples-Wpf#99]
All I want to do is register a view with a region. Nowhere in the docs is this explained well at all. I've been at this for 30 minutes now and the documentation is straight up terrible.
https://prismlibrary.com/docs/wpf/view-composition.html#defining-regions

```csharp
this.regionManager.RegisterViewWithRegion("MainRegion", typeof(EmployeeView));
```

What is _this_ in this context? Doesn't explain it. If you try to call this during the CreateShell invocation, before you resolve the main window (aka shell), you get an exception thrown.

```csharp
// View discovery
this.regionManager.RegisterViewWithRegion("MainRegion", () => this.container.Resolve<EmployeeView>());
```
Again, what the heck is _this_? Is it the PrismApplication? A window that got some service injected that you stored a reference to region manager and then ran that code during the constructor?

```csharp
// View injection
IRegion region = regionManager.Regions["MainRegion"];

var ordersView = container.Resolve<OrdersView>();
region.Add(ordersView, "OrdersView");
region.Activate(ordersView);
```
Wonderful! this looks like you can just slap this in the CreateShell method and be done! Nope! Throws an exception about how the region MainRegion does not exist. How great is that, right?

## Going to the github examples

Ok great, we have ourselves some git examples! Surely I'll be able to just look at App.xaml.cs and MainWindow.xaml.cs/.xaml and know what to do, right? Wrong!

Looking at https://github.com/PrismLibrary/Prism-Samples-Wpf/blob/master/02-Regions/Regions
The only line that has to do with regions is in MainWindow.xaml.cs:
```csharp
 <ContentControl prism:RegionManager.RegionName="ContentRegion" />
```
If you only place that in there, you will get an exception thrown about how ContentRegion does not exist.

ALL I WANT TO DO IS REGISTER A SIMPLE VIEW / VIEW MODEL WITH A SINGLE REGION!!!!! WHY IS IT SO DIFFICULT?

**Comment by brianlagunas** [comment]
Well that’s a rude way of asking for help.

**Comment by dsynclabsllc** [comment]
Don't worry, I used ChatGPT and it told me right away what to do. It was infinitely better than the docs written by the author!
